name: Fetch Lotto History

on:
  workflow_dispatch:   # 👈 allows manual trigger from GitHub Actions tab

permissions:
  contents: write

jobs:
  fetch-history:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true   # 👈 keep GITHUB_TOKEN so we can push


      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install axios cheerio

      - name: Run history scraper
        run: node scripts/fetch-history.js

      - name: Commit and push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.json
          git commit -m "Add historical lotto results" || echo "No changes to commit"
          git pull --rebase --autostash origin main
          git push
